name: Code Formatter and Syntax Check
on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
            cd Code/backend
            npm install
      - name: Lint
        run: |
            cd Code/backend
            npx eslint ./controllers
      - name: Changing path
        run: |
            pwd
            cd Code/frontend
      - name: Lint Frontend
        run: |
            npm install --force
            npx eslint . --fix
